
(ns tables
    (:use clojure.core))

; A bunch of static data gathered from the rules and the source.
    
(defrecord Skill [name id learning-time req-nps sub-skills usage-template])
(defn make-skill 
    ([name id learning-time] 
        (make-skill name id learning-time 0 nil nil))
	([name id learning-time req-nps sub-skills] 
        (make-skill name id learning-time req-nps sub-skills nil))
    ([name id learning-time req-nps sub-skills usage-template] 
        (Skill. name id learning-time req-nps sub-skills usage-template)))
		
(def skills
    [
    (make-skill "Shipcraft"             600 3 0 
		[
		  (make-skill "Sailing"             601  2)
		  (make-skill "Shipbuilding"        602  2)
		  (make-skill "Fishing"             603  2)
		]) 
    (make-skill "Combat"                610 3 0
		[
		   (make-skill "Survive fatal wound" 611 4)
		   (make-skill "Fight to the death"  612 4)
		   (make-skill "Construct catapult"  613 2)
		   (make-skill "Defense" 			 614 2)
		   (make-skill "Archery" 			 615 3)
		   (make-skill "Swordplay" 			 616 2)
		   (make-skill "Weaponsmithing" 	 617 2)
		])
    (make-skill "Stealth"               630 4 0 
		[
		   (make-skill "Petty thievery" 					631  2)
		   (make-skill "Determine inventory of character" 	632  2)
		   (make-skill "Determine skills of character" 		633  2)
		   (make-skill "Determine character's lord" 		634  2)
		   (make-skill "Conceal faction" 					635  4)
		   (make-skill "Learn of richest nearby noble" 		636  2)
		   (make-skill "Torture prisoner" 					637  3)
		   (make-skill "Sneak into structure" 				639  3)
		   (make-skill "Conceal self" 						641  4)
		]) 
    (make-skill "Beastmastery"          650 4 1 
		[
			(make-skill "Bird spy" 						651 3)
			(make-skill "Capture beasts in battle" 		652 4)
			(make-skill "Use beasts in battle" 			653 4)
			(make-skill "Breed beasts" 					654 4)
			(make-skill "Catch wild horses" 				655 2)
			(make-skill "Train wild horse to riding horse" 656 2)
			(make-skill "Train wild horse to warmount" 	657 3)
			(make-skill "Summon wild men" 					658 3)
			(make-skill "Persuade wild men to remain" 		659 3)
			(make-skill "Breed hound" 						661 3)
		])
    (make-skill "Persuasion"            670 4 0 
		[
			(make-skill "Bribe noble" 				671 2)
			(make-skill "Persuade oathbound noble" 672 3)
			(make-skill "Raise peasant mob" 		673 2)
			(make-skill "Rally peasant mob" 		674 3)
			(make-skill "Incite mob violence" 		675 3)
			(make-skill "Train angry peasants" 	676 2)
		]) 
    (make-skill "Construction"          680 3 0
		[
			(make-skill "Construct siege tower" 681  2)
			(make-skill "Stone quarrying" 		682  2)
		]) 
    (make-skill "Alchemy"               690 4 0 
		[ 
			(make-skill "Extract venom from ratspider" 	691 3)
			(make-skill "Make potion of slavery" 		692 3)
			(make-skill "Brew healing potion" 			693 3)
			(make-skill "Brew potion of death" 			694 3)
			(make-skill "Record skill on scroll" 		695 3)
			(make-skill "Collect rare elements" 		696 2)
			(make-skill "Turn lead into gold" 			697 4)
		]) 
    (make-skill "Forestry"              700 3 0 
		[
			(make-skill "Construct battering ram" 	701  2)
			(make-skill "Harvest lumber" 			702  2)
			(make-skill "Harvest yew" 				703  2)
			(make-skill "Collect rare foliage" 		704  2)
			(make-skill "Harvest mallorn wood" 		705  2)
			(make-skill "Harvest opium" 			706  2)
			(make-skill "Improve opium production" 	707  2)
		]) 
    (make-skill "Mining"                720 3 0
		[
			(make-skill "Mine iron" 			721 2)
			(make-skill "Mine gold" 			722 2)
			(make-skill "Mine mithril" 			723 2)
		]) 
    (make-skill "Trade"                 730 3 0 
		[
			(make-skill "Conceal identity of trader" 731 2)
			(make-skill "Find tradegood for sale" 	 732 2)
			(make-skill "Find market for tradegood"  733 2)
		]) 
    (make-skill "Religion"              750 5 1 
		[
			(make-skill "Receive vision" 				751 4)
			(make-skill "Resurrect dead noble" 			752 4)
			(make-skill "Preparatory ritual" 			753 3)
			(make-skill "Lay to rest" 					754 4)
			(make-skill "Remove blessing from soldiers" 755 4)
			(make-skill "Immunity from Vision" 			756 4)
		])
    (make-skill "Magic"                 800 4 1 
		[
			(make-skill "Meditate" 							801 2)
			(make-skill "Perform common tasks for gold" 	802 2)
			(make-skill "Appear common" 					803 2)
			(make-skill "View current aura level of others" 804 3)
			(make-skill "Heal" 								805 3)
			(make-skill "Modern magic script" 				806 3)
			(make-skill "Reveal abilities of another mage" 	807 2)
			(make-skill "Tap health for aura" 				808 3)
			(make-skill "Shroud abilities from scry" 		809 3)
			(make-skill "Detect ability scry" 				811 3)
			(make-skill "Dispel ability shroud" 			812 3)
			(make-skill "Advanced meditation" 				813 3)
			(make-skill "Hinder meditation" 				814 3)
		]) 
    (make-skill "Weather magic"         820 5 1
		[
			(make-skill "Fierce wind" 				821 3)
			(make-skill "Bind storm to ship" 		822 3)
			(make-skill "Scribe weather symbols" 	823 3)
			(make-skill "Summon rain" 				824 3)
			(make-skill "Summon wind" 				825 3)
			(make-skill "Summon fog" 				826 3)
			(make-skill "Direct storm" 				827 3)
			(make-skill "Dissipate storm" 			828 3)
			(make-skill "Renew storm strength" 		829 3)
			(make-skill "Lightning bolt" 			831 4)
			(make-skill "Seize control of storm" 	832 3)
			(make-skill "Fog of death" 				833 3)
		]) 
    (make-skill "Scrying"               840 5 1 
		[
			(make-skill "Scry location" 						841 3)
			(make-skill "Shroud location from magical scry" 	842 2)
			(make-skill "Dispel location shroud" 				843 3)
			(make-skill "Ciphered writing of Areth-Pirn" 		844 3)
			(make-skill "Create magical barrier" 				845 3)
			(make-skill "Remove magical barrier" 				846 3)
			(make-skill "Locate character" 						847 3)
			(make-skill "Detect location scry" 					848 3)
			(make-skill "Farcasting" 							849 3)
			(make-skill "Save farcast state" 					851 3)
			(make-skill "Banish undead" 						852 3)
		]) 
    (make-skill "Gatecraft"             860 5 1
		[
			(make-skill "Detect gates" 					861 2)
			(make-skill "Jump through gate"				862 2)
			(make-skill "Language of the Ancients" 		863 3)
			(make-skill "Seal gate" 					864 2)
			(make-skill "Unseal gate with key" 			865 2)
			(make-skill "Notify if gate unsealed" 		866 2)
			(make-skill "Forcefully unseal gate" 		867 3)
			(make-skill "Reveal gate key" 				868 3)
			(make-skill "Notify of gate jumps" 			869 2)
			(make-skill "Teleport"				 		871 2)
			(make-skill "Reverse jump through gate" 	872 3)
		]) 
    (make-skill "Artifact construction" 880 6 1
		[
			(make-skill "Forge auraculum" 					881 2)
			(make-skill "Reveal creator of artifact" 		882 2)
			(make-skill "Reveal where artifact was created" 883 2)
			(make-skill "Cloak creator of artifact" 		884 4)
			(make-skill "Cloak region of artifact creation" 885 2)
			(make-skill "Curse noncreator loyalty" 			886 2)
			(make-skill "Forge magical weapon" 				887 3)
			(make-skill "Forge magical armor" 				888 3)
			(make-skill "Forge magical bow" 				889 3)
			(make-skill "Dispel cloaking from artifact" 	891 3)
			(make-skill "Arcane symbols" 					892 3)
			(make-skill "Destroy artifact" 					893 3)
			(make-skill "Forge palantir" 					894 3)
		]) 
    (make-skill "Necromancy"            900 6 2 
		[
			(make-skill "Transcend death" 				901 4 1 nil)
			(make-skill "Runes of Evil" 				902 3)
			(make-skill "Summon ghost warriors" 		903 3)
			(make-skill "Raise undead" 					904 3)
			(make-skill "Summon demon lord" 			905 3)
			(make-skill "Renew demon bond" 				906 3)
			(make-skill "Banish demon lord" 			907 3)
			(make-skill "Eating of the dead" 			908 4)
			(make-skill "Aura blast" 					909 3)
			(make-skill "Absorb aura blast" 			911 3)
		])
    (make-skill "Advanced sorcery"      920 6 0
		[
			(make-skill "Trance" 			921 4)
			(make-skill "Teleport items" 	922 4)
		])
    ])
     
    
(defrecord Quest [where what at-least at-most])

(def quests
    [
    (Quest. "island"         24     5     30)
    (Quest. "island"         291 1     5)
    (Quest. "cave"             279 10     50)
    (Quest. "cave"             289 3     10)
    (Quest. "cave"             81     5     20)
    (Quest. "cave"             288 3     5 )
    (Quest. "cave"             287 5     20)
    (Quest. "ruins"         283 2     10)
    (Quest. "ruins"         291 2     5 )
    (Quest. "ruins"         272 3     10)
    (Quest. "ruins"         271    3     10)
    (Quest. "ruins"         282    1     3 )
    (Quest. "battlefield"   33    10     100)
    (Quest. "battlefield"     26    5     50 )
    (Quest. "battlefield"     292    3     10 )
    (Quest. "battlefield"     55    5     20 )
    (Quest. "graveyard"        31    10     100 )
    (Quest. "graveyard"     285    3     10 )
    (Quest. "graveyard"     278    3     10 )
    (Quest. "graveyard"     281    1     3 )
    (Quest. "lair"             280    3     8 )
    (Quest. "lair"             284    2     10 )
    (Quest. "lair"             286    1     1 )
    (Quest. "enchanted forest"     293    5     20 )
    (Quest. "enchanted forest"     25    5     20 )
    (Quest. "faery hill"     293    5     20 )
    (Quest. "faery hill"     25    5     20 )
    (Quest. "pits"             279    5     25 )
    (Quest. "pits"             288    3     7 )
    (Quest. "pits"             291    2     3 )
    (Quest. "pits"             272    1     5 )
    (Quest. "bog"             279    5     25 )
    (Quest. "bog"             288    3     7 )
    (Quest. "bog"             291    2     3 )
    (Quest. "bog"             272    1     5 )
    (Quest. "sand pit"         282    15     30 )
    (Quest. "circle of stone"         33    3     15 )
    (Quest. "circle of stone"         288    3     15 )
    (Quest. "circle of stone"         287    3     15 )
    (Quest. "circle of stone"         291    3     15 )
    (Quest. "circle of stone"         272    3     15 )
    (Quest. "circle of stone"         271    3     15 )
    (Quest. "circle of stone"         26    3     15 )
    (Quest. "circle of stone"         292    3     15 )
    (Quest. "circle of stone"         55    3     15 )
    (Quest. "circle of stone"         285    3     15 )
    (Quest. "circle of stone"         284     3    15 )
    (Quest. "chamber"                 279     10    50 ) ;actually level 1-6
    (Quest. "chamber"                 81     5    20 )
    (Quest. "chamber"                 288     3    6 )
    (Quest. "chamber"                 287     5    20 )
    (Quest. "tunnel chamber 5-6"     291     5    10 ) ;from here level 5-6 too...
    (Quest. "tunnel chamber 5-6"     272     5    15 )
    (Quest. "tunnel chamber 5-6"     282     5    15 )
    (Quest. "tunnel chamber 5-6"     278     5    15 )
    ])
    
(defrecord Creature [id name swamp man beast attack defense missile])

(def creatures
    [
    (Creature.    10    "peasant"            false       true      false     1    1    0)
    (Creature.    11    "worker"            false       true      false     1    1    0)
    (Creature.    12    "soldier"            false       true      false     5    5    0)
    (Creature.    13    "archer"            false       true      false     5    5    50)
    (Creature.    14    "knight"            false       true      false     45    45    0)
    (Creature.    15    "elite guard"        false       true      false     90    90    0    )
    (Creature.    16    "pikeman"            false       true      false     5    30    0)
    (Creature.    17    "blessed soldier"    false       true      false     5    5    0        )
    (Creature.    18    "ghost warrior"        false       true      false     0    0    0    )
    (Creature.    19    "sailor"            false       true      false     1    1    0)
    (Creature.    20    "swordsman"            false       true      false     15    15    0)
    (Creature.    21    "crossbowman"        false       true      false     1    1    25    )
    (Creature.    22    "elite archer"        false       true      false     10    10    75    )
    (Creature.    23     "angry peasant"    false       true      false     2    1    0        )
    (Creature.    24    "pirate"            false       true      false     5    5    0)
    (Creature.    25    "elf"                false       true      false     50    50    100    )
    (Creature.    26    "spirit"            false       true      false     50    50    0)
    (Creature.    31    "undead"            false       true      false     10    10    0)
    (Creature.    32    "savage"            false       true      false     1    1    0)
    (Creature.    33    "skeleton"            false       true      false     6    6    0)
    (Creature.    34    "barbarian"            false       true      false     2    1    0)
    (Creature.    51    "wild horse"        true          false     false     nil    nil    nil    )
    (Creature.    52    "riding horse"        true          false     false     nil    nil    nil    )
    (Creature.    53    "warmount"            true          false     false     nil    nil    nil)
    (Creature.    54    "winged horse"        true          false     false     nil    nil    nil    )
    (Creature.    55    "nazgul"            true          false     true        80    80    0        )
    (Creature.    60    "battering ram"        false       false     false     30    250    0            )
    (Creature.    61    "catapult"            false       false     false     25    200    25        )
    (Creature.    62    "siege tower"        false       false     false     30    250    0            )
    (Creature.    62    "siege tower"        false       false     false     30    250    0            )
    (Creature.    76    "ox"                true          false     false     nil    nil    nil    )
    (Creature.    81    "ratspider"            false       false     true        5    5    0)
    (Creature.    271    "centaur"             true          false     true        30    30    0)
    (Creature.    272    "minotaur"             true          false     true        30    5    0)
    (Creature.    278     "giant spider"     true          false     true        150    100    0        )
    (Creature.    279    "rat"                 true          false     true        3    3    0    )
    (Creature.    280    "lion"                 true          false     true        100    100    0    )
    (Creature.    281    "giant bird"         true          false     true        200    150    0    )
    (Creature.    282     "giant lizard"     true          false     true        45    45    0        )
    (Creature.    283    "bandit"             false       true      false     3    3    0)
    (Creature.    284    "chimera"             true          false     true        130    130    0)
    (Creature.    285    "harpie"             true          false     true        80    120    0)
    (Creature.    286    "dragon"             true          false     true        500    500    250    )
    (Creature.    287    "orc"                 false       true      true        20    15    0    )
    (Creature.    288    "gorgon"            true          false     true        10    20    0        )
    (Creature.    289    "wolf"                 true          false     true        5    5    0    )
    (Creature.    291    "cyclops"             false       true      true        25    75    0        )
    (Creature.    292    "giant"             false       true      true        75    25    0        )
    (Creature.    293    "faery"                false       true      false     9    9    9    )
    (Creature.    295    "hound"             true          false     false     1    1    0        )
    ])
    
(defrecord Item [id name weight land ride fly])

(def items
    [
    (Item.    1 "gold"     0    0    0    0)
    (Item.   10 "peasant"   100  100    0    0)
    (Item.   11 "worker"   100  100    0    0)
    (Item.   12 "soldier"   100  100    0    0)
    (Item.   13 "archer"   100  100    0    0)
    (Item.   14 "knight"   400  100  100    0)
    (Item.   15 "elite guard"   400  100  100    0)
    (Item.   16 "pikeman"   100  100    0    0)
    (Item.   17 "blessed soldier"   100  100    0    0)
    (Item.   18 "ghost warrior"     0    0    0    0)
    (Item.   19 "sailor"   100  100    0    0)
    (Item.   20 "swordsman"   100  100    0    0)
    (Item.   21 "crossbowman"   100  100    0    0)
    (Item.   22 "elite archer"   100  100    0    0)
    (Item.   23 "angry peasant"   100  100    0    0)
    (Item.   24 "pirate"   100  100    0    0)
    (Item.   25 "elf"   100  100    0    0)
    (Item.   26 "spirit"   100  100    0    0)
    (Item.   31 "undead"   100  100    0    0)
    (Item.   32 "savage"   100  100    0    0)
    (Item.   33 "skeleton"   100  100    0    0)
    (Item.   34 "barbarian"   100  100    0    0)
    (Item.   51 "wild horse" 1000   -1   -1    0)
    (Item.   52 "riding horse" 1000  150  150    0)
    (Item.   53 "warmount" 1000  150  150    0)
    (Item.   54 "winged horse" 1000  150  150  150)
    (Item.   55 "nazgul" 1500  150  150  150)
    (Item.   59 "flotsam"    30    0    0    0)
    (Item.   60 "battering ram"   300    0    0    0)
    (Item.   61 "catapult"   300    0    0    0)
    (Item.   62 "siege tower"   300    0    0    0)
    (Item.   63 "ratspider venom"     0    0    0    0)
    (Item.   64 "lana bark"     1    0    0    0)
    (Item.   65 "avinia leaf"     1    0    0    0)
    (Item.   66 "spiny root"     1    0    0    0)
    (Item.   67 "farrenstone"     1    0    0    0)
    (Item.   68 "yew"     3    0    0    0)
    (Item.   69 "elfstone"     1    0    0    0)
    (Item.   70 "mallorn wood"    30    0    0    0)
    (Item.   71 "pretus bones"     1    0    0    0)
    (Item.   72 "longbow"     3    0    0    0)
    (Item.   73 "plate armor"     5    0    0    0)
    (Item.   74 "longsword"     5    0    0    0)
    (Item.   75 "pike"     5    0    0    0)
    (Item.   76 "ox"  2000 1500   -1    0)
    (Item.   77 "wood"    30    0    0    0)
    (Item.   78 "stone"   100    0    0    0)
    (Item.   79 "iron"    10    0    0    0)
    (Item.   80 "leather"    30    0    0    0)
    (Item.   81 "ratspider"     1    0    0    0)
    (Item.   82 "mithril"     5    0    0    0)
    (Item.   83 "gate crystal"     1    0    0    0)
    (Item.   84 "blank scroll"     2    0    0    0)
    (Item.   85 "crossbow"    10    0    0    0)
    (Item.   87 "fish"     2    0    0    0)
    (Item.   93 "opium"     1    0    0    0)
    (Item.   94 "woven basket"     1    0    0    0)
    (Item.   95 "clay pot"     5    0    0    0)
    (Item.   96 "tax cookie"     0    0    0    0)
    (Item.   98 "drum"     2    0    0    0)
    (Item.   99 "hide"    50    0    0    0)
    (Item.  101 "mob cookie"     0    0    0    0)
    (Item.  102 "lead"    10    0    0    0)
    (Item.  261 "pitch"   100    0    0    0)
    (Item.  271 "centaur"  1000  150  150    0)
    (Item.  272 "minotaur"   800   -1   -1    0)
    (Item.  273 "undead cookie"     0    0    0    0)
    (Item.  274 "fog cookie"     0    0    0    0)
    (Item.  275 "wind cookie"     0    0    0    0)
    (Item.  276 "rain cookie"     0    0    0    0)
    (Item.  277 "mage menial cookie"     0    0    0    0)
    (Item.  278 "giant spider"   500   -1   -1    0)
    (Item.  279 "rat"    50   -1   -1    0)
    (Item.  280 "lion"   750   -1   -1    0)
    (Item.  281 "giant bird"  1500   -1   -1   -1)
    (Item.  282 "giant lizard"  1000   -1   -1    0)
    (Item.  283 "bandit"   100  100    0    0)
    (Item.  284 "chimera"   800   -1   -1    0)
    (Item.  285 "harpie"   500   -1   -1   -1)
    (Item.  286 "dragon"  2500   -1   -1   -1)
    (Item.  287 "orc"   100  100   -1    0)
    (Item.  288 "gorgon"   200   -1   -1    0)
    (Item.  289 "wolf"   100   -1   -1    0)
    (Item.  290 "crystal orb"     1    0    0    0)
    (Item.  291 "cyclops"   200  200    0    0)
    (Item.  292 "giant"   200  200    0    0)
    (Item.  293 "faery"    10   10    0    0)
    (Item.  294 "petty thief cookie"     0    0    0    0)
    (Item.  295 "hound"    65   -1    0    0)
    (Item.  401 "Imperial Throne"     0    0    0    0)
    ])

           
(defrecord InnerLoc [province-type subloc-type weight hidden])

(def innerlocs
    [
    (InnerLoc. "desert"     "cave"              10     :yes)
    (InnerLoc. "desert"     "oasis"             10     :rnd)
    (InnerLoc. "desert"     "sand pit"          10     :rnd)
    (InnerLoc. "mountain"   "ruins"             10     :yes)
    (InnerLoc. "mountain"   "cave"              10     :yes)
    (InnerLoc. "mountain"   "yew grove"         10     :rnd)
    (InnerLoc. "mountain"   "lair"              10     :rnd)
    (InnerLoc. "mountain"   "battlefield"       6      :rnd)
    (InnerLoc. "swamp"      "bog"               10     :rnd)
    (InnerLoc. "swamp"      "pits"              10     :rnd)
    (InnerLoc. "swamp"      "battlefield"       6      :rnd)
    (InnerLoc. "swamp"      "lair"              5      :rnd)
    (InnerLoc. "swamp"      "lair"              3      :yes)
    (InnerLoc. "forest"     "ruins"             10     :yes)
    (InnerLoc. "forest"     "circle of trees"   10     :yes)
    (InnerLoc. "forest"     "enchanted forest"  10     :yes)
    (InnerLoc. "forest"     "yew grove"         10     :rnd)
    (InnerLoc. "forest"     "cave"              10     :yes)
    (InnerLoc. "forest"     "mallorn grove"     9      :yes)
    (InnerLoc. "forest"     "battlefield"       6      :rnd)
    (InnerLoc. "plain"      "ruins"             10     :yes)
    (InnerLoc. "plain"      "pasture"           10     :no)
    (InnerLoc. "plain"      "rocky hill"        10     :no)
    (InnerLoc. "plain"      "sacred grove"      10     :rnd)
    (InnerLoc. "plain"      "poppy field"       10     :no)
    (InnerLoc. "plain"      "cave"              10     :yes)
    (InnerLoc. "plain"      "battlefield"       6      :rnd)
    ])
    
(defrecord Production [location-type item-id quantity])

(def productions
    [
    (Production. "forest"         	77	30)
    (Production. "sacred grove"   	77	5)
    (Production. "circle of trees"	77	5)
    (Production. "mountain"       	78	50)
    (Production. "rocky hill"     	78	50)
    (Production. "desert"         	78	10)
    (Production. "cave"           	67	2)
    (Production. "plain"          	51	5)
    (Production. "pasture"        	51	5)
    (Production. "ocean"          	87	50)
    (Production. "mallorn grove"  	65	2)
    (Production. "mallorn grove"  	70	2)
    (Production. "bog"            	66	4)
    (Production. "pits"           	66	4)
    (Production. "swamp"          	66	1)
    (Production. "yew grove"      	68	5)
    (Production. "graveyard"      	31	15)
    (Production. "circle of trees"	64	3)
    (Production. "sand pit"       	71	1)
    (Production. "poppy field"    	93	25)
    (Production. "forest"         	10	10)
    (Production. "mountain"       	10	10)
    (Production. "plain"          	10	10)
    (Production. "city"           	10	10)
    ])
    
    